clone_folder: C:\projects\libcmaes
environment:
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"

install:
  - cinstall: python
  - vcpkg install eigen3

build_script:
  - cd c:\projects\libcmaes
  - mkdir build && cd build
  - cmake -G "%CMAKE_PLATFORM%" -DCMAKE_INSTALL_PREFIX=c:\Libraries\libcmaes -DEigen3_ROOT=c:\Libraries\eigen\share\eigen3\cmake -DBOOST_ROOT="C:/Libraries/boost_1_63_0" ..
  - cmake --build . --config Release --target install
  - ctest -C Release
